# basics
host: # your name. used to identify provider resources
app_path: ./
provider: aws

# aws 
aws_ec2_key: # name of AWS Key Pair
aws_vpc_limit: 
aws_ami_nat: 
aws_ami_ubuntu: 
aws_s3_bucket: 
aws_s3_endpoint: 